version: '3.9'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    networks:
      - lineoa-klaeng-network
    volumes:
      - /app/node_modules
      - .:/app
      - ./certs:/etc/nginx/certs

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: docker compose run certbot certonly --webroot --webroot-path=/var/www/html --email chirayu.chomsri@gmail.com --agree-tos --no-eff-email -d c2.pea-klaeng.com -d www.c2.pea-klaeng.com


networks:
  lineoa-klaeng-network:


