version: '3.9'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    networks:
      - lineoa-klaeng-network
    volumes:
      - /app/node_modules
      - .:/app
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - frontend
    command: certonly --webroot --webroot-path=/var/www/html --email chirayu.chomsri@gmail.com --agree-tos --no-eff-email --staging -d c2.pea-klaeng.com  -d www.c2.pea-klaeng.com

volumes:
  web-root:
  certbot-etc:
  certbot-var:

networks:
  lineoa-klaeng-network:


