version: '3.9'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:80"
    restart: on-failure
    networks:
      - lineoa-klaeng-network
    volumes:
      - .:/usr/src/app/lineoa-klaeng/frontend

networks:
  lineoa-klaeng-network:


