version: '3.9'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - lineoa-klaeng-network
    volumes:
      - /app/node_modules
      - .:/app

networks:
  lineoa-klaeng-network:

